---  # LGD-VAE local debug (macOS/MPS)

experiment:
  task: "lgd_vae_generation_local"
  seed: 42
  note: "Local debug for Latent-Gated Dual-VAE (small batch/epochs)"

paths:
  data_root: "/Users/qiuchuanhang/PycharmProjects/AALTD2025imbalance/UCR_Imbalanced_9_1"
  work_root: "/Users/qiuchuanhang/PycharmProjects/tsml-eval/local/LGD_VAE"
  logs_dir: "/Users/qiuchuanhang/PycharmProjects/tsml-eval/local/LGD_VAE/logs"
  ckpt_dir: "/Users/qiuchuanhang/PycharmProjects/tsml-eval/local/LGD_VAE/checkpoints"
  outputs_dir: "/Users/qiuchuanhang/PycharmProjects/tsml-eval/local/LGD_VAE/samples"

data:
  dataset_name: "FiftyWords"          # 本地先固定一个小数据集，或用 CLI 覆盖
  format: "ucr"
  # —— 关键：从 data.loader.* 挪到 data 顶层 ——
  train_batch_size: 32
  eval_batch_size: 128
  loader_workers: 4
  train_dataset:
    shuffle: true

  # 其余原来的字段保留（若你用得到）
  train_suffix: "_TRAIN.ts"
  test_suffix: "_TEST.ts"
  in_channels: 1
  normalize: "zscore_from_train"
  sampling_time: 30

  # 可保留或先关掉（我们代码默认不依赖）
  windowing:
    use_sliding_window: false

model:
  # Encoder
  in_chans: 1
  embed_dim: 64          # 原 d_model
  depth: 3               # 原 enc_depth
  num_heads: 4           # 原 n_heads
  d_hid: 256             # Latents
  latent_dim_global: 32
  latent_dim_class: 32
  # Gating head
  gate_hidden: 64
  # Decoder
  decoder_embed_dim: 64  # 原 dec_dim
  decoder_depth: 3       # 原 dec_depth
  decoder_num_heads: 4   # 若无单独 dec_heads 就与 num_heads 一致

  # Conv1d embedder (由我们在 Embedder 中实现)
  kernel_size: 3         # 原 conv.kernel_size
  stride: 1              # 原 conv.stride
  padding: 1             # 原 conv.padding

  # Regularization / layout
  dropout: 0.1
  norm_first: true
  # Initialization & extras

  # Loss weights（见 pl_model 中对应 log 键）
  align_lambda: 0.05       # \lambda_align，用于 \mathcal{L}_{align} 0.10 /0.05
  cls_lambda: 1.0          # 若不开类别监督，这里为 0
  kl_g_lambda: 0.5         # 全局 KL 系数（beta-VAE 风格） 0.05/0.01
  kl_c_lambda: 0.5         # 类别 KL 系数
  recon_lambda: 1.00        # 重构项系数
  disentangle_lambda: 0.10  # 0.10
  center_lambda: 0.01       # 0.01
  # Other flags
  minority_class_id: 1      # 你的少数类 id（UCR 使用 np.unique 后得到的索引）
  cls_embed: true
  recon_metric: "mse"   # 同loss recon_metric, works here soft_dtw, dilate, mse

loss:
  type: "lgd_vae_default"
  recon_metric: "mse"   # 同 model.recon_metric
  huber_delta: 1.0

optim:
  optimizer: "adamw"
  lr: 0.001
  weight_decay: 0.01
  betas: [0.9, 0.999]
  scheduler: "cosine"
  cosine:
    T_max: 100              # 对齐本地 epochs
    eta_min: 1e-5
    warmup_epochs: 10

trainer:
  max_epochs: 100
  accelerator: "auto"
  devices: 1
  strategy: "auto"
  log_every_n_steps: 5
  check_val_every_n_epoch: 1
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0

callbacks:
  checkpointing:
    dirpath: "/Users/qiuchuanhang/PycharmProjects/tsml-eval/local/LGD_VAE/checkpoints"
    filename: "MGD_CVAE-{epoch:02d}"
    monitor: "eval_f1_min"
    mode: "max"
    save_top_k: 1
    save_last: true
    every_n_epochs: 1
#    warmup_epochs: 20

  early_stopping:
    monitor: "train_recon_loss"
    mode: "min"
    patience: 5
    min_delta: 0.0
    warmup_epochs: 5
logging:
  use_tensorboard: true
  project: "MGD_CVAE-ucr"
  run_name: null

impute_infer:
  write_outputs: true
  save_format: "npy"

repro:
  cudnn_benchmark: false
  seed: 42

ddp:
  find_unused_parameters: false
  broadcast_buffers: false
